using Lint
using Base.Test

include( "bitopbool.jl" )
include( "deadcode.jl" )
include( "deprecate.jl" )
include( "dictkey.jl" )
include( "dupexport.jl" )
include( "forloop.jl")
include( "funcall.jl")
include( "globals.jl")
include( "ifstmt.jl")
include( "lambda.jl")
include( "lintself.jl")
include( "mathconst.jl")
include( "meta.jl" )
include( "range.jl")
include( "similarity.jl" )
include( "strings.jl")
include( "symbol.jl")
include( "type.jl")
include( "undeclare.jl" )
include( "unusedvar.jl")
include( "using.jl")
