using Lint
using Base.Test

println( "test basic printing and sorting of lint messages")
include( "show.jl" )
println( "test core lint functionalities" )
include( "bitopbool.jl" )
include( "comprehensions.jl")
include( "deadcode.jl" )
include( "deprecate.jl" )
include( "dictkey.jl" )
include( "dupexport.jl" )
include( "forloop.jl")
include( "funcall.jl")
include( "globals.jl")
include( "ifstmt.jl")
include( "lambda.jl")
include( "macro.jl" )
include( "mathconst.jl")
include( "module.jl" )
include( "meta.jl" )
include( "pragma.jl" )
include( "range.jl")
include( "similarity.jl" )
include( "strings.jl")
include( "symbol.jl")
include( "type.jl")
include( "undeclare.jl" )
include( "unusedvar.jl")
include( "using.jl")

include( "lintself.jl")
