# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Lint")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --compiled-modules=no -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Lint"); Pkg.test("Lint"; coverage=true)'
    - julia -e 'using Lint'  # loading after precompilation
